### ISSUE TITLE
Parellel edges are allowed?

### ISSUE THREAD

**Issue by GdRottoli** [lady-bluecopper/ReSuM#1]
In the paper associated where this algorithm is presented, the authors define the graph with its edgeset into the cross product VxV, so parallel edges aren't allowed.
Is this so? or the implementation allows to consider different edges whit the same endpoints?
Thanks a lot.

**Comment by lady-bluecopper** [comment]
Hello,
we do not allow parallel edges, i.e., two nodes can be connected by a single edge.
Regards
